### ISSUE TITLE
安装NSQQ后点开私聊消息小红点提示不会消失

### ISSUE THREAD

**Issue by postyizhan** [Night-stars-1/LiteLoaderQQNT-Plugin-NSQQ#2]
请看视频
我没有尝试让其他人复现这个问题（
尝试过重装QQNT和LiteLoaderQQNT
[视频.zip](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-NSQQ/files/14157532/default.zip)

**Comment by Night-stars-1** [comment]
你机器人账号又不会一直看，这些又不影响

**Comment by postyizhan** [comment]
> 你机器人账号又不会一直看，这些又不影响

哈哈好吧

**Comment by Night-stars-1** [comment]
> > 你机器人账号又不会一直看，这些又不影响
> 
> 哈哈好吧

之后可能会修复，目前这个插件优先级不高，没有功能上的bug不太会更新
