### ISSUE TITLE
如何发送消息还有图片，好像和gocqhttp协议有一些出入。

### ISSUE THREAD

**Issue by HuangArmagh** [Night-stars-1/LiteLoaderQQNT-Plugin-NSQQ#5]
我自己写的机器人连接gocqhttp发送这个是可以发出消息的，但是接入了这个好像不太行。 
{"action":"send_group_msg","params":{"group_id":666666,"message":1111111111}}
{"action":"send_group_msg","params":{"group_id":666666,"message":"[CQ:image,file=http://baidu.com/1.jpg,cache=0]"}}
是有什么改动或者需要注意的吗？

**Comment by Night-stars-1** [comment]
> 我自己写的机器人连接gocqhttp发送这个是可以发出消息的，但是接入了这个好像不太行。 {"action":"send_group_msg","params":{"group_id":666666,"message":1111111111}} {"action":"send_group_msg","params":{"group_id":666666,"message":"[CQ:image,file=http://baidu.com/1.jpg,cache=0]"}} 是有什么改动或者需要注意的吗？

你接入的机器人是什么，他好像不会解析cq码

**Comment by HuangArmagh** [comment]
我自己用JS写的机器人，有没有这个插件的文档我可以自己接入，比如要发送什么具体的参数才可以发送文字或者图片。

**Comment by Night-stars-1** [comment]
> 我自己用JS写的机器人，有没有这个插件的文档我可以自己接入，比如要发送什么具体的参数才可以发送文字或者图片。

```json
{"action":"send_msg","params":{"group_id":123456,"message":[{"type":"image","data":{"file":"http://baidu.com/1.jpg"}}]},"echo":"0c194bbf-af83-4f2c-ab54-e413b80a7731"}
```

**Comment by HuangArmagh** [comment]
> > 我自己用JS写的机器人，有没有这个插件的文档我可以自己接入，比如要发送什么具体的参数才可以发送文字或者图片。
> 
> ```json
> {"action":"send_msg","params":{"group_id":123456,"message":[{"type":"image","data":{"file":"http://baidu.com/1.jpg"}}]},"echo":"0c194bbf-af83-4f2c-ab54-e413b80a7731"}
> ```

哦哦，我懂了，gocqhttp有好几个发送消息的接口。/send_private_msg     /send_group_msg     /send_msg

**Comment by Night-stars-1** [comment]
> > > 我自己用JS写的机器人，有没有这个插件的文档我可以自己接入，比如要发送什么具体的参数才可以发送文字或者图片。
> > 
> > 
> > ```json
> > {"action":"send_msg","params":{"group_id":123456,"message":[{"type":"image","data":{"file":"http://baidu.com/1.jpg"}}]},"echo":"0c194bbf-af83-4f2c-ab54-e413b80a7731"}
> > ```
> 
> 哦哦，我懂了，gocqhttp有好几个发送消息的接口。/send_private_msg /send_group_msg /send_msg

这个虽然是go-cqhttp协议，但我参考的插件似乎更贴近onebot11协议，另外cq码已经过时了，解析成json是不错的选择

**Comment by HuangArmagh** [comment]
> > > > 我自己用JS写的机器人，有没有这个插件的文档我可以自己接入，比如要发送什么具体的参数才可以发送文字或者图片。
> > > 
> > > 
> > > ```json
> > > {"action":"send_msg","params":{"group_id":123456,"message":[{"type":"image","data":{"file":"http://baidu.com/1.jpg"}}]},"echo":"0c194bbf-af83-4f2c-ab54-e413b80a7731"}
> > > ```
> > 
> > 
> > 哦哦，我懂了，gocqhttp有好几个发送消息的接口。/send_private_msg /send_group_msg /send_msg
> 
> 这个虽然是go-cqhttp协议，但我参考的插件似乎更贴近onebot11协议，另外cq码已经过时了，解析成json是不错的选择

我刚才把代码改了试了下确实还是不行echo这个一定要有吗？我用其他ws客户端测试返回的确实是正确的格式。{"action":"send_msg","params":{"group_id":666666,"message":[{"type":"text","data":{"text":"66"}}]}}返回给插件这个信息但是插件就是发不出消息。

**Comment by HuangArmagh** [comment]
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-NSQQ/assets/31194798/fb4a44dd-ba27-4e7c-bad4-b061a7beca26)
接收数据的时候这里会显示信息吗？

**Comment by Night-stars-1** [comment]
> ![image](https://private-user-images.githubusercontent.com/31194798/305705557-fb4a44dd-ba27-4e7c-bad4-b061a7beca26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjU3MzUsIm5iZiI6MTcwODMyNTQzNSwicGF0aCI6Ii8zMTE5NDc5OC8zMDU3MDU1NTctZmI0YTQ0ZGQtYmEyNy00ZTdjLWJhZDQtYjA2MWE3YmVjYTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA2NTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NDBmZmZhYjVhY2RjNDM5NzFlNjNiZmRkMWFkNjFhYTAwNzU5OWJiZmIzMGVmMDI1ODM3MjBhNTRmM2JiZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r0rwfxPIHfk83GqaAqTWOVC0xJA6Fzo49gCCHltpMEA) 我加了echo一样不行，还有插件接收数据的时候这里会显示信息吗？我看插件发送的时候有提示，但是接收的时候没有。

安装最新版，然后在配置文件里打开debug，看一下控制台的输出

**Comment by Night-stars-1** [comment]
另外我参考的实现是
https://github.com/TimeRainStarSky/Yunzai/blob/main/plugins/adapter/go-cqhttp.js

**Comment by HuangArmagh** [comment]
可能是我写的ws服务端有问题，不过我用其他几个ws客户端连接收发信息功能都是正常的，可能是我对于反向ws的理解不够深吧，最后chatgpt推荐我用WebSocketServer.broadcast，终于解决了。
